name: Deploy

defaults:
  run:
    working-directory: ./VueApp

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']


# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./VueApp
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build CSS variables from master JSON
        run: npm run build-variables

      - name: Commit CSS variables changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Dmitry-Sokolov
          author_email: dmytro@neuronux.com
          message: 'Css variables added'
          add: '*.css'

      - name: Build project
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook -- -o dist/storybook

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload dist repository
          path: './VueApp/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

# token: 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
