name: Deploy Storybook

on:
  push:
    branches:
      - "main" # change to the branch you wish to deploy from

defaults:
  run:
    working-directory: ./VueApp

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./VueApp
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.2
        with:
          path: ./VueApp # change to your build folder
          install_command: npm install
          build_command: npm run build-storybook
          checkout: false # default: true