name: Deploy Storybook

defaults:
  run:
    working-directory: ./VueApp

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']


# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./VueApp
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.2
        with:
          path: './VueApp/dist' # change to your build folder
          install_command: npm install
          build_command: npm run build-storybook
          checkout: false # default: true